name: Lint

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linters
        continue-on-error: false
        run: |
          black --check fitmap tests stravad.py
          flake8 fitmap tests stravad.py
